title: Klyve
description: The Desktop Software Development Factory.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# UPDATED CONFIGURATION
url: "https://klyve.online"
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/social-preview.png"
baseurl: ""
logo: "/assets/images/favicon.ico"
favicon_ico: "/assets/images/favicon.ico"

# Navigation Logic
nav_sort: nav_order

# Enable Search
search_enabled: true

# Top Right Navigation Links
# Changed to "Releases" since source is not public
aux_links:
  "Releases":
    - "https://github.com/klyvedev/klyve/releases"

# Footer
footer_content: "Â© 2025 Mario J. Lewis. All rights reserved. <a href='mailto:developer@klyve.online' style='text-decoration: underline;'>developer@klyve.online</a>"

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
